# Generated by Django 6.0.5 on 2026-05-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('car', 'Personal Car'), ('taxi', 'Taxi'), ('coaster', 'Coaster'), ('boda', 'Boda-boda')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('number_plate', models.CharField(max_length=10, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('nin', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
